name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: {python-version: ${{ matrix.python-version }}}
      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ hashFiles('**/pyproject.toml') }}
      - name: Install deps
        run: |
          pip install poetry
          poetry install --with dev
      - name: Lint / format
        run: |
          poetry run ruff src tests
          poetry run black --check src tests
      - name: Tests
        run: poetry run pytest --cov=src
